### ISSUE TITLE
Update not working...

### ISSUE THREAD

**Issue by ThunderBRZ** [regimbal93/cPanelDDNS-PHP-Client#1]
Hi Regimbal...

Many thx 4 ur code... work´s... but have 1 issue :

If ip address need update, this script ADD 1 more "A" dns record with same name, not update exist record.
sorry my poor english
[]´s

**Comment by ThunderBRZ** [comment]
$zones = $this->cpanel->api2_query($this->config['cpanel']['account'],'ZoneEdit', 'fetchzones')->data->zones->{'regimbal.me'};

this is a zone regimbal.me ???

**Comment by dregimbal1** [comment]
Hey mate,

Sorry for the late response. Thanks for pointing this out! I pushed updated changes to reflect these issues. It should all be working well. Let me know!

Best wishes,
Dave
